# Generated by Django 5.0.6 on 2024-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cell', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('visited_u', models.IntegerField()),
                ('description', models.TextField()),
                ('nid_passport_image', models.ImageField(upload_to='nid_passport_images/')),
            ],
        ),
    ]
