# Generated by Django 5.0.6 on 2024-05-31 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number_of_rooms', models.IntegerField()),
                ('images', models.JSONField()),
                ('facilities', models.TextField()),
                ('promo', models.CharField(max_length=100)),
                ('area_or_location', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel_owner.hotelowner')),
            ],
        ),
    ]
